CREATE TABLE AWARD_EXT_T (
AWARD_ID            DECIMAL(12,0) NOT NULL,
CUSTOMFIELD_1       VARCHAR(30),
CUSTOMFIELD_2       VARCHAR(30),    
OBJ_ID              VARCHAR(36) NOT NULL,   
VER_NBR         	  DECIMAL(8) DEFAULT 1 NOT NULL,
PRIMARY KEY (AWARD_ID)
);
